### ISSUE TITLE
sparql in the template renku-values.yaml file

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku-admin-docs#11]
be ready for sparql for next time (notice the ordering of the alias &  reference, let's keep that):

```
  graph:
     sparql:
      username: admin
      password: &sparql-password <somepassword>
...
 graph:
  jena:
    admin:
      password: *sparql-password
```

this issue is a reminder, please resolve once included
